### ISSUE TITLE
One time multiple hosts adding in wpi-custom - create problem

### ISSUE THREAD

**Issue by vehvekz** [wpi-pw/vagrant#1]
Problem with creating multiple projects in one time. I mean if I add some projects in wpi-custom and set status on 'create' for all of them, after run 'vagrant reload' install compleate for only first from list.

**Comment by DimaMinka** [comment]
the vagrant updated and part of scripts moved to wpi cloud...
https://github.com/wpi-pw/vagrant/commit/da44dfc1be9e5528a6f4ad4cd919fb8c7e53863b
https://github.com/wpi-pw/vagrant/commit/15363136fb7d2adf75fc3af7187c39e219e0a509
